#! /usr/bin/env bash
# Check that upload targets work as expected
#


check_upload_cleanup()
{
    rm -rf ${test_startdir}/tests/proj
}

# Check upload_targets
check_upload_targets()
{
    run; dno >make.log 2>&1 || fail "upload target prep fails"
    grep -q OBJCOPY make.log || fail "upload target does not create image"
    run; dno upload DEVICE_PATH=/dev/wibble --dry-run >make.log 2>&1 ||
	fail "upload target dryrun fails"
    grep -q "avrdude.*-patmega328p.*-Uflash:w:build/blink.hex:i" make.log ||
	fail "upload command not found in make output."
    # Now upload using programmer
    run; dno uploadp DEVICE_PATH=/dev/wibble \
	PROGRAMMER=arduinoasisp --dry-run >make.log 2>&1 ||
	fail "uploadp target dryrun fails"
    grep -q "avrdude.*-cstk500v1.*-Uflash:w:build/blink.hex:i" make.log ||
	fail "uploadp command not found in make output."
}

check_upload()
{
    echo -n "Checking upload targets"
    cd ${test_startdir}
    mkdir -p tests/proj/blink
    cd tests/proj/blink
    cp ${SCRIPTDIR}/assets/src/blink.cpp .
    mkdir -p arduino.pro
    cd arduino.pro
    check_upload_targets
}
