#! /usr/bin/env bash
# Check that docs biuld targets do as expected
#


check_boot_cleanup()
{
    rm -rf ${test_startdir}/tests/proj
}

# Check boot targets
check_boot_targets()
{
    cd boot
    run; dno >make.log 2>&1 || fail "Simple boot build fails"
    grep -q avr-objdump make.log || fail "Boot build: no avr-objdump performed"
    [ -f optiboot_atmega328.hex ] || fail "Boot build: no hex file created"
    run; dno clean >make.log 2>&1 || fail "dno clean fails in boot dir"
    [ -f optiboot_atmega328.hex ] && fail "Boot clean: hex file not removed"
    run; dno >make.log 2>&1 || fail "Explicit boot build fails"
    grep -q avr-objdump make.log ||
	fail "Boot build: no avr-objdump performed (2)"
    [ -f optiboot_atmega328.hex ] ||
	fail "Boot build: no hex file created (2)"

    mkdir docs
    cp ${SCRIPTDIR}/assets/docs/Doxyfile docs
    run; dno docs >make.log 2>&1 || fail "boot docs build fails"
    grep -q "<title>optiboot" docs/html/index.html ||
	fail "boot docs build: no \"optiboot\" title"
    run; dno clean >make.log 2>&1 || fail "dno clean fails in boot dir (2)"
    cd docs
    run; dno >make.log 2>&1 || fail "Implicit boot docs build fails"
    grep -q "<title>optiboot" html/index.html ||
	fail "boot docs build: no \"optiboot\" title"
}

check_boot()
{
    echo -n "Checking boot builds"
    cd ${test_startdir}
    mkdir -p tests/proj/blink
    cd tests/proj/blink
    echo avr.pro >BOARD_TYPE
    cp ${SCRIPTDIR}/assets/src/blink.cpp .
    cp -r ${SCRIPTDIR}/assets/boot .
    check_boot_targets
}
